// flow-typed signature: fb3c0434c5d810a8eabfd2ce917a80a8
// flow-typed version: <<STUB>>/wdio-chromedriver-service_v^0.1.3/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wdio-chromedriver-service'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wdio-chromedriver-service' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wdio-chromedriver-service/build/launcher' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/build/utils/getFilePath' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/gruntfile' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/launcher' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/test/integration/main.spec' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/test/integration/wdio.conf' {
  declare module.exports: any;
}

declare module 'wdio-chromedriver-service/test/unit/utils/getFilePath.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wdio-chromedriver-service/build/launcher.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/build/launcher'>;
}
declare module 'wdio-chromedriver-service/build/utils/getFilePath.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/build/utils/getFilePath'>;
}
declare module 'wdio-chromedriver-service/gruntfile.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/gruntfile'>;
}
declare module 'wdio-chromedriver-service/index' {
  declare module.exports: $Exports<'wdio-chromedriver-service'>;
}
declare module 'wdio-chromedriver-service/index.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service'>;
}
declare module 'wdio-chromedriver-service/launcher.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/launcher'>;
}
declare module 'wdio-chromedriver-service/test/integration/main.spec.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/test/integration/main.spec'>;
}
declare module 'wdio-chromedriver-service/test/integration/wdio.conf.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/test/integration/wdio.conf'>;
}
declare module 'wdio-chromedriver-service/test/unit/utils/getFilePath.spec.js' {
  declare module.exports: $Exports<'wdio-chromedriver-service/test/unit/utils/getFilePath.spec'>;
}
